### ISSUE TITLE
Can't install Fugashi and error "ModuleNotFoundError: No module named 'questionary'"

### ISSUE THREAD

**Issue by m4t7w** [Arpitpandey992/VGMDB-Auto-Tagger#3]
Hello and thank you for working on this.

I have a problem: i cannot install the requirments "fugashi" and "aiohttp".

Im on Python v. 3.12.3 with pip 24.0 (windows 10).

I solved aiohttp by installing the latest version (3.9.5), but i was unable to install succesfully fugashi. 
```
ERROR: Failed building wheel for fugashi
Failed to build fugashi
ERROR: Could not build wheels for fugashi, which is required to install pyproject.toml-based projects
```

And when i try to start album_tagger.py i get this error: `import questionary ModuleNotFoundError: No module named 'questionary'`

**Comment by Arpitpandey992** [comment]
Hey, sorry I just came across this issue.
I was having this issue as well earlier. I believe we need to specifically use python3.11 for the dependencies to be built properly.
Please use `python3.11 -m venv .venv` to create a virtual environment instead.

The docker image for vgmdb.info was also giving some issues. I'll update the README I guess

**Comment by Arpitpandey992** [comment]
@m4t7w I have updated the documentation and dependencies. It should work with python3.12 out of the box now. Also, the issue with running the docker image of vgmdb.info by Hufman is also fixed (running it using docker-compose now).
Just make sure that docker is installed in your system and docker-compose is also installed (it is included with docker desktop, need to install it manually if using Linux or docker's cli package)

**Comment by m4t7w** [comment]
Thank you! I was just about to comment that it's running fine now

**Comment by Arpitpandey992** [comment]
Glad to know that :)
